backend:
  name: github
  repo: gargnitya/Interlegere
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "writing"
    label: "Writing"
    folder: "content/writing"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "photography"
    label: "Photography"
    folder: "content/photography"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Caption", name: "caption", widget: "string" }

  - name: "productdesign"
    label: "Product Design"
    folder: "content/productdesign"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }

  - name: "personalprojects"
    label: "Personal Projects"
    folder: "content/personalprojects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Progress", name: "progress", widget: "number" }
      - { label: "Body", name: "body", widget: "markdown" }
